### ISSUE TITLE
import doesn't seem to really be supported

### ISSUE THREAD

**Issue by seamusmalone** [Shidil/cocos-es6#3]
in app.js the HelloWorld scene is local... and the HelloWorldScene.js file doesn't seem to be referenced anywhere... if I try to import into app.js I get Uncaught SyntaxError: Unexpected token import.
Is this actually working anywhere?

**Comment by shidil** [comment]
hi @seamusmalone 

HelloWorldScene is referenced in src/index.js


This repo is now old and hasn't been updated to meet the new versions of libraries. I am glad someone found a use case to have es6 on cocos2d-x.

If you are fine with using cocos creator you will have TypeScript support inbuilt for that. Regardless of that this repo had it's own purpose when I wrote it and I am willing to update it to the latest.

**Comment by shidil** [comment]
PR #4

**Comment by shidil** [comment]
@seamusmalone Project is now updated and working again
